# Generated by Django 5.1.6 on 2025-03-30 21:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(blank=True, max_length=255, null=True)),
                ('activity_type', models.CharField(choices=[('view', 'View'), ('search', 'Search'), ('add_to_cart', 'Add to Cart'), ('purchase', 'Purchase')], max_length=50)),
                ('search_query', models.CharField(blank=True, max_length=255, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.category')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.product')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'User Activities',
                'indexes': [models.Index(fields=['user'], name='user_activity_user_idx'), models.Index(fields=['session_id'], name='user_activity_session_idx'), models.Index(fields=['activity_type'], name='user_activity_type_idx'), models.Index(fields=['timestamp'], name='user_activity_time_idx')],
            },
        ),
    ]
