# Generated by Django 5.1.6 on 2025-04-01 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_updated_at'),
    ]

    operations = [
    ]
